import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class NewsClusteringTest {
    NewsClustering nc = new NewsClustering();
    @Test
    public void testCase() {
        //assertEquals(16384, nc.solution("FRANCE","french"));
        //assertEquals(65536, nc.solution("handshake","shake hands"));
        //assertEquals(43690, nc.solution("aa1+aa2","AAAA12"));
        //assertEquals(65536, nc.solution("E=M*C^2","e=m*c^2"));
        assertEquals(65536, nc.solution("asdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdxasdfzxcvdx",
                "asdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksxasdfkmnksx"));
    }
}
